const waitScene = async (p, key, max = 40) => { for (let i = 0; i < max; i++) { await p.waitForTimeout(500); const s = await p.evaluate(() => window.__game?.scene.getScenes(true).map(s => s.scene.key).join(',')); if (s === key) return true; } return false; };
const G = 'window.__game.scene.getScene("Game")';
export const steps = [
  async (p) => { await p.evaluate(() => localStorage.setItem('steelmeridian.save.slot3', '{"version":1,"state":{"cities":[]}}')); await p.reload(); await waitScene(p, 'Menu'); await p.click('[data-a="new"]'); await p.click('[data-v="atl"]'); await p.click('[data-a="diff"][data-v="hard"]'); await p.click('[data-a="start"]'); return 'started ' + await waitScene(p, 'Game'); },
  async (p) => { await p.waitForTimeout(800); await p.click('[data-a="speed"][data-v="4"]'); await p.waitForTimeout(300); const a = await p.evaluate(`(${G}).sim.state.speed`); await p.click('[data-a="speed"][data-v="0"]'); const paused = await p.evaluate(`(${G}).sim.state.paused`); await p.keyboard.press('Space'); const resumed = !(await p.evaluate(`(${G}).sim.state.paused`)); return { speed4: a === 4, paused, resumed, difficulty: await p.evaluate(`(${G}).sim.state.difficulty`) }; },
  async (p) => { await p.click('[data-a="market"]'); await p.waitForTimeout(300); const before = await p.evaluate(`(${G}).sim.state.factions.atl.res.metal`); await p.click('[data-a="trade"][data-v="metal:100"]'); const after = await p.evaluate(`(${G}).sim.state.factions.atl.res.metal`); await p.keyboard.press('Escape'); return { boughtMetal: Math.round(after - before) }; },
  async (p) => { await p.click('[data-a="factions"]'); await p.waitForTimeout(300); await p.screenshot({ path: 'scripts/.out/40-diplomacy.png' }); await p.click('[data-a="peace"][data-v="sco"]'); await p.waitForTimeout(200); const rel = await p.evaluate(`(${G}).sim.state.relations['atl|sco']`); await p.keyboard.press('Escape'); return { relationAfterProposal: rel }; },
  async (p) => { await p.keyboard.press('Escape'); await p.waitForTimeout(300); const paused = await p.evaluate(`(${G}).sim.state.paused`); await p.click('[data-a="settings"]'); await p.waitForTimeout(300); await p.click('[data-a="toggle"][data-v="showFps"]'); await p.screenshot({ path: 'scripts/.out/41-settings.png' }); await p.keyboard.press('Escape'); await p.waitForTimeout(200); return { pausedByMenu: paused, fpsSetting: await p.evaluate(() => JSON.parse(localStorage.getItem('steelmeridian.settings')).showFps) }; },
  async (p) => p.evaluate(() => { const sc = __game.scene.getScene('Game'); const s = sc.sim.state; s.paused = false; let hiddenSubs = 0, shownSubs = 0, detected = 0; for (const v of sc.unitViews.all()) { const u = v.unit; if (u.type !== 'submarine' || u.owner === s.player) continue; const vis = sc.unitViews.isVisibleToPlayer(u); if (vis) shownSubs++; else hiddenSubs++; if (u.detMask & sc.sim.combat.bit(s.player)) detected++; } return { enemySubsHidden: hiddenSubs, enemySubsShown: shownSubs, detected }; }),
  async (p) => { const r = await p.evaluate(() => { const sc = __game.scene.getScene('Game'); const bad = sc.sim && JSON.stringify(Object.keys(sc)); return typeof bad; }); return r; },
  async (p) => { await p.setViewportSize({ width: 1280, height: 720 }); await p.waitForTimeout(1500); await p.screenshot({ path: 'scripts/.out/42-1280.png' }); await p.setViewportSize({ width: 1920, height: 1080 }); await p.waitForTimeout(1500); await p.screenshot({ path: 'scripts/.out/43-1920.png' }); return p.evaluate(() => ({ w: __game.scale.width, h: __game.scale.height })); },
  async (p) => { await p.keyboard.press('F3'); await p.waitForTimeout(500); await p.screenshot({ path: 'scripts/.out/44-debug.png' }); await p.click('[data-d="win"]'); await p.waitForTimeout(600); await p.screenshot({ path: 'scripts/.out/45-victory.png' }); return 'victory shown ' + await p.evaluate(() => !!document.querySelector('.gameover')); },
  async (p) => { await p.keyboard.press('F5'); await p.click('.gameover [data-a="quit"]'); await waitScene(p, 'Menu'); await p.waitForTimeout(600); await p.screenshot({ path: 'scripts/.out/46-menu-continue.png' }); const hasContinue = await p.evaluate(() => !!document.querySelector('[data-a="continue"]')); await p.click('[data-a="load"]'); await p.waitForTimeout(300); const slots = await p.evaluate(() => [...document.querySelectorAll('.save-slot .nm')].map(e => e.textContent)); await p.click('.save-slot [data-a="load"]'); const ok = await waitScene(p, 'Game'); return { hasContinue, slots, loadedGame: ok }; },
];
